from __future__ import annotations

from typing import Any, Protocol
from uuid import UUID

from app.domain.catalog import Agent, Skill
from app.domain.execution import ExecutionPlan, ExecutionSubmission
from app.domain.knowledge import KnowledgeBase, KnowledgeChunk, KnowledgeDocument, RetrievalHit
from app.domain.prompt import Prompt
from app.domain.tool import McpServer, Tool


class ExecutionRepositoryPort(Protocol):
    async def create_execution(self, submission: ExecutionSubmission) -> tuple[UUID, bool]: ...
    async def claim_next(self) -> dict[str, Any] | None: ...
    async def complete(self, execution: dict[str, Any], *, normalized_intent: str, result: dict[str, Any]) -> None: ...
    async def fail(self, execution: dict[str, Any], error: dict[str, Any]) -> None: ...
    async def get(self, execution_id: UUID) -> dict[str, Any] | None: ...
    async def pending_outbox(self, limit: int = 50) -> list[dict[str, Any]]: ...
    async def mark_published(self, event_id: UUID) -> None: ...
    async def mark_publish_attempt(self, event_id: UUID) -> None: ...


class CatalogRepositoryPort(Protocol):
    async def list_skills(self, enabled_only: bool = False) -> list[Skill]: ...
    async def get_skill(self, skill_id: UUID) -> Skill | None: ...
    async def get_skill_by_name(self, name: str) -> Skill | None: ...
    async def create_skill(self, skill: Skill) -> Skill: ...
    async def update_skill(self, skill: Skill) -> Skill: ...
    async def delete_skill(self, skill_id: UUID) -> bool: ...
    async def list_agents(self, enabled_only: bool = False) -> list[Agent]: ...
    async def get_agent(self, agent_id: UUID) -> Agent | None: ...
    async def get_agent_by_name(self, name: str) -> Agent | None: ...
    async def create_agent(self, agent: Agent, skill_names: list[str]) -> Agent: ...
    async def update_agent(self, agent: Agent, skill_names: list[str]) -> Agent: ...
    async def delete_agent(self, agent_id: UUID) -> bool: ...


class PromptRepositoryPort(Protocol):
    async def list_prompts(self) -> list[Prompt]: ...
    async def get_prompt(self, prompt_id: UUID) -> Prompt | None: ...
    async def get_prompt_by_name(self, name: str) -> Prompt | None: ...
    async def create_prompt(self, prompt: Prompt) -> Prompt: ...
    async def update_prompt(self, prompt: Prompt) -> Prompt: ...
    async def delete_prompt(self, prompt_id: UUID) -> bool: ...


class ToolRepositoryPort(Protocol):
    async def list_tools(self, enabled_only: bool = False) -> list[Tool]: ...
    async def get_tool(self, tool_id: UUID) -> Tool | None: ...
    async def get_tool_by_name(self, name: str) -> Tool | None: ...
    async def create_tool(self, tool: Tool) -> Tool: ...
    async def update_tool(self, tool: Tool) -> Tool: ...
    async def delete_tool(self, tool_id: UUID) -> bool: ...

    async def list_mcp_servers(self, enabled_only: bool = False) -> list[McpServer]: ...
    async def get_mcp_server(self, server_id: UUID) -> McpServer | None: ...
    async def get_mcp_server_by_name(self, name: str) -> McpServer | None: ...
    async def create_mcp_server(self, server: McpServer) -> McpServer: ...
    async def update_mcp_server(self, server: McpServer) -> McpServer: ...
    async def delete_mcp_server(self, server_id: UUID) -> bool: ...


class ToolExecutorPort(Protocol):
    async def execute(self, tool: Tool, arguments: dict[str, Any]) -> dict[str, Any]: ...


class ModelGatewayPort(Protocol):
    async def complete(
        self,
        *,
        system_prompt: str,
        user_prompt: str,
        model_profile: str,
        temperature: float = 0.2,
    ) -> str: ...
    async def execute(self, plan: ExecutionPlan) -> dict[str, Any]: ...
    async def close(self) -> None: ...


class EventPublisherPort(Protocol):
    async def publish_json(self, subject: str, payload: dict[str, Any]) -> None: ...


class KnowledgeRepositoryPort(Protocol):
    async def list_knowledge_bases(self, enabled_only: bool = False) -> list[KnowledgeBase]: ...
    async def get_knowledge_base(self, kb_id: UUID) -> KnowledgeBase | None: ...
    async def get_knowledge_base_by_name(self, name: str) -> KnowledgeBase | None: ...
    async def create_knowledge_base(self, kb: KnowledgeBase) -> KnowledgeBase: ...
    async def update_knowledge_base(self, kb: KnowledgeBase) -> KnowledgeBase: ...
    async def delete_knowledge_base(self, kb_id: UUID) -> bool: ...
    async def list_expired_knowledge_bases(self) -> list[KnowledgeBase]: ...
    async def list_documents(self, kb_id: UUID) -> list[KnowledgeDocument]: ...
    async def get_document(self, document_id: UUID) -> KnowledgeDocument | None: ...
    async def get_document_by_source(self, kb_id: UUID, source_type: str, source_id: str) -> KnowledgeDocument | None: ...
    async def create_document(self, document: KnowledgeDocument) -> KnowledgeDocument: ...
    async def update_document_content(self, document_id: UUID, **kwargs) -> KnowledgeDocument | None: ...
    async def mark_document_pending(self, document_id: UUID) -> bool: ...
    async def claim_next_document(self) -> KnowledgeDocument | None: ...
    async def complete_document(self, document_id: UUID, chunks: list[KnowledgeChunk], *, parsed_metadata: dict[str, Any]) -> None: ...
    async def fail_document(self, document_id: UUID, error: dict[str, Any]) -> None: ...
    async def delete_document(self, document_id: UUID) -> bool: ...
    async def retrieve(self, knowledge_base_ids: list[UUID], *, query: str, query_embedding: list[float], limit: int) -> list[RetrievalHit]: ...
    async def agent_exists(self, agent_id: UUID) -> bool: ...
    async def replace_agent_knowledge_bases(self, agent_id: UUID, assignments: list[tuple[UUID, str]]) -> None: ...
    async def list_agent_knowledge_bases(self, agent_id: UUID) -> list[dict[str, Any]]: ...
