from __future__ import annotations

from typing import Any, Protocol
from uuid import UUID

from app.domain.execution import ExecutionPlan, ExecutionSubmission


class ExecutionRepositoryPort(Protocol):
    async def create_execution(self, submission: ExecutionSubmission) -> tuple[UUID, bool]: ...
    async def claim_next(self) -> dict[str, Any] | None: ...
    async def complete(
        self,
        execution: dict[str, Any],
        *,
        normalized_intent: str,
        result: dict[str, Any],
    ) -> None: ...
    async def fail(self, execution: dict[str, Any], error: dict[str, Any]) -> None: ...
    async def get(self, execution_id: UUID) -> dict[str, Any] | None: ...
    async def pending_outbox(self, limit: int = 50) -> list[dict[str, Any]]: ...
    async def mark_published(self, event_id: UUID) -> None: ...
    async def mark_publish_attempt(self, event_id: UUID) -> None: ...


class ModelGatewayPort(Protocol):
    async def execute(self, plan: ExecutionPlan) -> dict[str, Any]: ...
    async def close(self) -> None: ...


class EventPublisherPort(Protocol):
    async def publish_json(self, subject: str, payload: dict[str, Any]) -> None: ...
