from __future__ import annotations

from typing import Any, Protocol
from uuid import UUID

from app.domain.catalog import Agent, Skill
from app.domain.execution import ExecutionPlan, ExecutionSubmission
from app.domain.prompt import Prompt


class ExecutionRepositoryPort(Protocol):
    async def create_execution(self, submission: ExecutionSubmission) -> tuple[UUID, bool]: ...
    async def claim_next(self) -> dict[str, Any] | None: ...
    async def complete(self, execution: dict[str, Any], *, normalized_intent: str, result: dict[str, Any]) -> None: ...
    async def fail(self, execution: dict[str, Any], error: dict[str, Any]) -> None: ...
    async def get(self, execution_id: UUID) -> dict[str, Any] | None: ...
    async def pending_outbox(self, limit: int = 50) -> list[dict[str, Any]]: ...
    async def mark_published(self, event_id: UUID) -> None: ...
    async def mark_publish_attempt(self, event_id: UUID) -> None: ...


class CatalogRepositoryPort(Protocol):
    async def list_skills(self, enabled_only: bool = False) -> list[Skill]: ...
    async def get_skill(self, skill_id: UUID) -> Skill | None: ...
    async def get_skill_by_name(self, name: str) -> Skill | None: ...
    async def create_skill(self, skill: Skill) -> Skill: ...
    async def update_skill(self, skill: Skill) -> Skill: ...
    async def delete_skill(self, skill_id: UUID) -> bool: ...
    async def list_agents(self, enabled_only: bool = False) -> list[Agent]: ...
    async def get_agent(self, agent_id: UUID) -> Agent | None: ...
    async def get_agent_by_name(self, name: str) -> Agent | None: ...
    async def create_agent(self, agent: Agent, skill_names: list[str]) -> Agent: ...
    async def update_agent(self, agent: Agent, skill_names: list[str]) -> Agent: ...
    async def delete_agent(self, agent_id: UUID) -> bool: ...


class PromptRepositoryPort(Protocol):
    async def list_prompts(self) -> list[Prompt]: ...
    async def get_prompt(self, prompt_id: UUID) -> Prompt | None: ...
    async def get_prompt_by_name(self, name: str) -> Prompt | None: ...
    async def create_prompt(self, prompt: Prompt) -> Prompt: ...
    async def update_prompt(self, prompt: Prompt) -> Prompt: ...
    async def delete_prompt(self, prompt_id: UUID) -> bool: ...


class ModelGatewayPort(Protocol):
    async def complete(self, *, system_prompt: str, user_prompt: str, model_profile: str, temperature: float = 0.2) -> str: ...
    async def execute(self, plan: ExecutionPlan) -> dict[str, Any]: ...
    async def close(self) -> None: ...


class EventPublisherPort(Protocol):
    async def publish_json(self, subject: str, payload: dict[str, Any]) -> None: ...
